import { Inter } from "next/font/google";
import "./globals.css";
import Navrbar from "@/components/Navrbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, members, dashboard }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navrbar />
        <main>
          <div className="parallel">
            {members}
            {dashboard}
          </div>
          {children}

        </main>
      </body>
    </html>
  );
}
